# Database
db=dev-file

# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP
https-certificate-file=/etc/letsencrypt/live/poegel.dev/fullchain.pem
https-certificate-key-file=/etc/letsencrypt/live/poegel.dev/privkey.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
# hostname=https://login.oldno.name
# hostname-admin=https://login.poegel.dev
hostname-strict=false
